### PR TITLE
Fixes to headings, WIP, refs #19

### PR DESCRIPTION
**Pull request by sobolevn**
There are several changes that I made:
1. Removed `.hack { word-wrap: break-word; }` rule, placed this rule inside `body`
2. Set `line-height: 1.3em` to all the headers, which fixes the #19 issue

Does `1.3em` look good to you? Any other comments?

### CODE REVIEW

**Comment by egoist** [comment]
What about set `1.3em` to all headers including the markdown mode and remove `line-height: 30px` for `.hack h1/h2`

**Comment by sobolevn** [comment]
That would totally be more consistent.

**Comment by egoist** [comment]
It looks good, I can merge it if you're sure no more issues.

**Comment by sobolevn** [comment]
I guess, that's it. Thanks!

**Comment by egoist** [comment]
Thanks for your nice work 👍🏻

**Pull request merged**
