### PR TITLE
Lighten background in dark theme

### PR DESCRIPTION
**Pull request by hhaslam11**
Disclaimer: I only half know what I'm doing.

### CODE REVIEW

**Comment by egoist** [comment]
Can you make a demo for this? It could be placed at `src/jade/$THEME_NAME.jade`

**Comment by hhaslam11** [comment]
It wasn't meant to be another theme, just a modification to [dark mode](http://hackcss.com/dark.html).
So, [dark.jade](https://github.com/egoist/hack/blob/master/src/html/dark.jade) _would_ be the demo.

this:
capture1
just turns into:
capture2

**Comment by egoist** [comment]
i.e. this should be another theme called `dark-grey.css` it'd better not replace the existing theme.

**Comment by hhaslam11** [comment]
Alright, sounds good. I'll work on that tonight!

**Comment by hhaslam11** [comment]
Maybe (probably) I'm doing something wrong, but when I try compiling the .jade files ([this](http://jade-lang.com/command-line/), right?), I get an error; something about `:marked` being an unknown filter.
capture
I think I got the demo page ready, but I don't want to commit anything without actually confirming everything is working..
I'm sort of a big noob with all this, as you can probably tell :P // it's new to me.

I'm probably being more of a pain than a help, but hey- I'm trying :P

**Comment by hhaslam11** [comment]
Alright, after screwing around enough, I got everything working fine.
demo page has been created, and `gulpfile.js` and readme has been updated.

Let me know if theres anything else that needs to be done.

**Comment by egoist** [comment]
Thanks for your work, it's merged. 😬

**Pull request closed without merging**
