### PR TITLE
Add a simple modal dialog component

### PR DESCRIPTION
**Pull request by sukima**
Really simple but useful Modal Dialog Box in 100% CSS

Screen Shot 2019-11-26 at 22 34 49
Screen Shot 2019-11-26 at 22 36 58
Screen Shot 2019-11-26 at 22 37 10
Screen Shot 2019-11-26 at 22 37 26
Screen Shot 2019-11-26 at 22 37 46

### CODE REVIEW

**Comment by mugiwarafx** [comment]
Great job m8! It looks cool 🤩

**Comment by sukima** [comment]
@mugiwarafx Thanks!. Question is will this get merged?!

**Comment by sukima** [comment]
Since it has been almost 11 months. I've stored a version of this on my personal site:

https://tritarget.org/files/cdn/hack/

**Comment by sukima** [comment]
I've forked and maintained my own copy here: https://github.com/sukima/hackcss-ext

**Comment by mugiwarafx** [comment]
Hi @sukima, I'm glad to hear that! I would love to contribute to your new fork. 

I guess the word "Dead" of the title there is nothing to do with title decoration and means this project is dead for @egoist.  

So, let's get down to work! 😁

**Pull request closed without merging**
